---

- name: Setup package repository
  import_tasks: setup-Debian.yml
  when:
    - ansible_os_family == "Debian"

- name: Setup package repository
  import_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == "RedHat"

- name: Install apt packages
  package:
    name: nvidia-container-toolkit
    state: present

- name: Restart docker service
  systemd:
    state: restarted
    name: docker

- name: Blacklist mod
  file:
    src: nvidia-installer-disable-nouveau.conf
    dest: /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
    mode: '0644'
    owner: root
    group: root

- name: Reboot for mod blacklist to take effect
  reboot:
    reboot_timeout: 3600

- stat:
    path: /lib/modules/*/kernel/drivers/video/nvidia-drm.ko
  register: nvidia_mod

- name: Retrieve driver
  get_url:
    url: http://us.download.nvidia.com/tesla/440.33.01/NVIDIA-Linux-x86_64-440.33.01.run
    dest: /tmp/nvidia_driver.run
    mode: 777
  when: not nvidia_mod.stat.exists

- name: Install driver
  command: /bin/bash /tmp/nvidia_driver.run -s
  when: not nvidia_mod.stat.exists