---

- name: Setup package repository
  import_tasks:
    name: "setup-{{ ansible_os_family }}.yml"

- name: Install apt packages
  package:
    name: nvidia-container-toolkit
    state: present

- name: Restart docker service
  systemd:
    state: started
    name: docker