---

- name: Setup package repository
  import_tasks: setup-Debian.yml
  when:
    - ansible_os_family == "Debian"

- name: Setup package repository
  import_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == "RedHat"

- name: Install apt packages
  package:
    name: 
      - nvidia-container-toolkit
      - nvidia-container-runtime
    state: present

- name: Add nvidia runtime to docker
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0664

- name: Restart docker service
  systemd:
    state: restarted
    name: docker