---

- name: Add apt gpg key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add apt source
  command: "curl -s -L https://nvidia.github.io/nvidia-docker/{{ os-release.stdout }}/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list"