---

- name: Import NVidia docker GPG signing key
  apt_key:
    url: "{{ nvidia_gpg_key_url }}"
    state: present

- name: Add NVidia docker repositories
  apt_repository:
    repo: "deb {{ nvidia_github_url }}/{{ item }}/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}/$(ARCH) /"
    state: present
  loop:
    - libnvidia-container
    - nvidia-container-runtime
    - nvidia-docker